language: php

dist: xenial

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

env:
  - COMPOSER_NO_INTERACTION=1

install:
  - travis_retry composer install --no-suggest

script:
  - composer validate --strict
  - find src -name *.php | xargs -n 1 php -l
  - vendor/bin/php-cs-fixer fix --dry-run
